### ISSUE TITLE
gun-show preview?

### ISSUE THREAD

**Issue by jonmalave** [88dev/gun-show#1]
@88dev can you add a screenshot to the README? Possibly maybe later a YouTube video showcasing how gun-show works and helps to visualize gundb....

**Comment by 88dev** [comment]
Hi Jon, thanks for the comment. Guess, the docs of gun-show match the ones of gun ;) Well, this one is at least up-to-date and clearly states what does not work/is not implemented.
Gun-show is just a demo to showcase the look and feel of a new generation of database viewers. To make it a "drop-in and use" thing, it would need a lot more work.

**Comment by jonmalave** [comment]
@88dev all good! still would be nice to visualize the data in anyway... better than nothing. Thanks for creating this.
